[package]
name = "arpegiator_pattern_receiver"
version = "0.1.0"
authors = ["Vincent Alsteen <vincent.alsteen@gmail.com>"]
edition = "2018"

[dependencies]
vst = { git = "https://github.com/rustaudio/vst-rs" }
util = { path = "../util" }
arpegiator = { path = "../arpegiator" }
build-info = "0.0.20"
log = "0.4.11"
serde = "1.0.118"
bincode = "1.3.1"

[build-dependencies]
build-info-build = "0.0.20"

[lib]
name = "arpegiator_pattern_receiver"
crate-type = ["cdylib", "lib"]
